[Target]
name=x86_64-musl-static
arch=x86_64
subarch=generic
abi=elf
float=hard
libc=musl
triplet=x86_64-unknown-linux-musl
deb_host_arch=amd64

[Paths]
sysroot=/mnt/runepkg/x86_64-musl-static/sysroot
crosstools=/mnt/runepkg/x86_64-musl-static/crosstools
cross_bin=/mnt/runepkg/x86_64-musl-static/crosstools/bin

[Environment]
CC=x86_64-unknown-linux-musl-gcc
CXX=x86_64-unknown-linux-musl-g++
LD=x86_64-unknown-linux-musl-ld
AR=x86_64-unknown-linux-musl-ar
RANLIB=x86_64-unknown-linux-musl-ranlib
STRIP=x86_64-unknown-linux-musl-strip
READELF=x86_64-unknown-linux-musl-readelf
CFLAGS=-O2 -static -fPIC -D_POSIX_C_SOURCE=200809L
CXXFLAGS=-O2 -static -fPIC -std=c++17 -D_POSIX_C_SOURCE=200809L
LDFLAGS=-static -static-libgcc -static-libstdc++ -Wl,--gc-sections
PKG_CONFIG_SYSROOT_DIR=/mnt/runepkg/x86_64-musl-static/sysroot
PKG_CONFIG_LIBDIR=/mnt/runepkg/x86_64-musl-static/sysroot/usr/lib/pkgconfig
