#!/usr/bin/env bash
#/******************************************************************************
# * Filename:    010-linux-headers
# * Author:      <michkochris@gmail.com>
# * Description: Linux API Headers for the crosstools forge sysroot
# ******************************************************************************/

. ./somelinuxconfig
somelinux_ensure_loaded

# --- Build Configuration ---
# Find kernel directory
KERNEL_DIR=$(find "$SOMESRC" -maxdepth 1 -name "linux-*" -type d | head -n 1)

if [[ -z "$KERNEL_DIR" ]]; then
    somelinux_exit "Kernel source directory not found in $SOMESRC"
fi

cd "$KERNEL_DIR" || somelinux_exit "Failed to enter kernel directory"

echo "  [forge] Installing sanitized Linux headers to $CLFS/usr/include..."
make mrproper
make ARCH=$(uname -m | sed -e 's/x86_64/x86/' -e 's/aarch64/arm64/' -e 's/armv7l/arm/') headers_install INSTALL_HDR_PATH="$CLFS/usr"

somelinux_exit "The forge ritual for linux-libc-dev headers is complete." 0
