#!/usr/bin/env bash
#/******************************************************************************
# * Filename:    013-gcc-pass2
# * Author:      <michkochris@gmail.com>
# * Description: GCC Pass 2 (Final) for the crosstools forge
# ******************************************************************************/

. ./somelinuxconfig
somelinux_ensure_loaded

# --- Build Configuration ---
# Find the rules file dynamically
RULES_PATH=$(find "$SOMESRC" -path "*/gcc-14-*/debian/rules" | head -n 1)

if [[ -f "$RULES_PATH" ]]; then
    echo "  [config] Updating debian/rules for GCC Pass 2..."
    cat << EOF > "$RULES_PATH"
#!/usr/bin/make -f
LDFLAGS += $(FORGE_LDFLAGS)
%:
	dh \$@

override_dh_auto_configure:
	dh_auto_configure -- \\
		--target=\$(CLFS_TARGET) \\
		--prefix=/crosstools \\
		--with-sysroot=\$(CLFS) \\
		--with-local-prefix=/crosstools \\
		--with-native-system-header-dir=/usr/include \\
		--enable-languages=c,c++ \\
		--disable-libstdcxx-pch \\
		--disable-nls \\
		--disable-multilib \\
		--with-gmp=/crosstools \\
		--with-mpfr=/crosstools \\
		--with-mpc=/crosstools \\
		--with-isl=/crosstools \\
		LDFLAGS="\$(LDFLAGS)"
EOF
    chmod +x "$RULES_PATH"

    echo "  [config] Adjusting .install files..."
    find "$(dirname "$RULES_PATH")" -name "*.install" -exec sed -i "s|^usr/|crosstools/|g" {} +
fi

# --- Build Automation ---
echo "  [forge] Ritual initiated: assembly of gcc-crosstools-final..."
runepkg buildpkg-split "gcc-14"

somelinux_exit "The forge ritual for gcc-crosstools-final is complete." 0
